[general]
live_config_reload=true

[window]
opacity=0.8

[font.bold]
family = "NotoSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font"
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

